"""
CineWorld Studio's - Extended Names Database
Migliaia di nomi per generare cast infiniti
"""

# Nomi estesi per ogni nazionalità (100+ per categoria)
EXTENDED_NAMES = {
    'USA': {
        'first_male': [
            'James', 'Robert', 'Michael', 'William', 'David', 'Richard', 'Joseph', 'Thomas', 'Christopher', 'Charles',
            'Daniel', 'Matthew', 'Anthony', 'Mark', 'Donald', 'Steven', 'Paul', 'Andrew', 'Joshua', 'Kenneth',
            'Kevin', 'Brian', 'George', 'Timothy', 'Ronald', 'Edward', 'Jason', 'Jeffrey', 'Ryan', 'Jacob',
            'Gary', 'Nicholas', 'Eric', 'Jonathan', 'Stephen', 'Larry', 'Justin', 'Scott', 'Brandon', 'Benjamin',
            'Samuel', 'Raymond', 'Gregory', 'Frank', 'Alexander', 'Patrick', 'Jack', 'Dennis', 'Jerry', 'Tyler',
            'Aaron', 'Jose', 'Adam', 'Nathan', 'Henry', 'Douglas', 'Zachary', 'Peter', 'Kyle', 'Ethan',
            'Jeremy', 'Walter', 'Christian', 'Keith', 'Roger', 'Terry', 'Austin', 'Sean', 'Gerald', 'Carl',
            'Harold', 'Dylan', 'Arthur', 'Lawrence', 'Jordan', 'Jesse', 'Bryan', 'Billy', 'Bruce', 'Gabriel',
            'Joe', 'Logan', 'Albert', 'Willie', 'Alan', 'Eugene', 'Russell', 'Vincent', 'Philip', 'Bobby',
            'Johnny', 'Bradley', 'Roy', 'Ralph', 'Randy', 'Louis', 'Howard', 'Eugene', 'Carlos', 'Russell',
        ],
        'first_female': [
            'Mary', 'Patricia', 'Jennifer', 'Linda', 'Barbara', 'Elizabeth', 'Susan', 'Jessica', 'Sarah', 'Karen',
            'Lisa', 'Nancy', 'Betty', 'Margaret', 'Sandra', 'Ashley', 'Kimberly', 'Emily', 'Donna', 'Michelle',
            'Dorothy', 'Carol', 'Amanda', 'Melissa', 'Deborah', 'Stephanie', 'Rebecca', 'Sharon', 'Laura', 'Cynthia',
            'Kathleen', 'Amy', 'Angela', 'Shirley', 'Anna', 'Brenda', 'Pamela', 'Emma', 'Nicole', 'Helen',
            'Samantha', 'Katherine', 'Christine', 'Debra', 'Rachel', 'Carolyn', 'Janet', 'Catherine', 'Maria', 'Heather',
            'Diane', 'Ruth', 'Julie', 'Olivia', 'Joyce', 'Virginia', 'Victoria', 'Kelly', 'Lauren', 'Christina',
            'Joan', 'Evelyn', 'Judith', 'Megan', 'Andrea', 'Cheryl', 'Hannah', 'Jacqueline', 'Martha', 'Gloria',
            'Teresa', 'Ann', 'Sara', 'Madison', 'Frances', 'Kathryn', 'Janice', 'Jean', 'Abigail', 'Alice',
            'Judy', 'Sophia', 'Grace', 'Denise', 'Amber', 'Doris', 'Marilyn', 'Danielle', 'Beverly', 'Isabella',
            'Theresa', 'Diana', 'Natalie', 'Brittany', 'Charlotte', 'Marie', 'Kayla', 'Alexis', 'Lori', 'Zoe',
        ],
        'last': [
            'Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis', 'Rodriguez', 'Martinez',
            'Hernandez', 'Lopez', 'Gonzalez', 'Wilson', 'Anderson', 'Thomas', 'Taylor', 'Moore', 'Jackson', 'Martin',
            'Lee', 'Perez', 'Thompson', 'White', 'Harris', 'Sanchez', 'Clark', 'Ramirez', 'Lewis', 'Robinson',
            'Walker', 'Young', 'Allen', 'King', 'Wright', 'Scott', 'Torres', 'Nguyen', 'Hill', 'Flores',
            'Green', 'Adams', 'Nelson', 'Baker', 'Hall', 'Rivera', 'Campbell', 'Mitchell', 'Carter', 'Roberts',
            'Gomez', 'Phillips', 'Evans', 'Turner', 'Diaz', 'Parker', 'Cruz', 'Edwards', 'Collins', 'Reyes',
            'Stewart', 'Morris', 'Morales', 'Murphy', 'Cook', 'Rogers', 'Gutierrez', 'Ortiz', 'Morgan', 'Cooper',
            'Peterson', 'Bailey', 'Reed', 'Kelly', 'Howard', 'Ramos', 'Kim', 'Cox', 'Ward', 'Richardson',
            'Watson', 'Brooks', 'Chavez', 'Wood', 'James', 'Bennett', 'Gray', 'Mendoza', 'Ruiz', 'Hughes',
            'Price', 'Alvarez', 'Castillo', 'Sanders', 'Patel', 'Myers', 'Long', 'Ross', 'Foster', 'Jimenez',
        ],
    },
    'UK': {
        'first_male': [
            'Oliver', 'George', 'Harry', 'Jack', 'Jacob', 'Noah', 'Charlie', 'Oscar', 'James', 'William',
            'Henry', 'Alexander', 'Thomas', 'Edward', 'Benjamin', 'Samuel', 'Daniel', 'Joseph', 'David', 'Alfie',
            'Leo', 'Lucas', 'Archie', 'Theo', 'Arthur', 'Freddie', 'Max', 'Isaac', 'Ethan', 'Sebastian',
            'Finley', 'Logan', 'Joshua', 'Harrison', 'Adam', 'Elijah', 'Toby', 'Dylan', 'Jayden', 'Harvey',
            'Louie', 'Reuben', 'Mason', 'Teddy', 'Bobby', 'Jude', 'Frankie', 'Hugo', 'Reggie', 'Stanley',
            'Albert', 'Lewis', 'Connor', 'Nathan', 'Louis', 'Luca', 'Caleb', 'Roman', 'Ezra', 'Riley',
            'Zachary', 'Elliott', 'Blake', 'Aaron', 'Ollie', 'Felix', 'Jasper', 'Ronnie', 'Jake', 'Albie',
            'Arlo', 'Austin', 'Cameron', 'Carter', 'Rupert', 'Jesse', 'Dominic', 'Kai', 'Alex', 'Rowan',
        ],
        'first_female': [
            'Olivia', 'Emma', 'Ava', 'Sophia', 'Isabella', 'Mia', 'Amelia', 'Charlotte', 'Emily', 'Grace',
            'Poppy', 'Lily', 'Ella', 'Freya', 'Sophie', 'Chloe', 'Lucy', 'Hannah', 'Phoebe', 'Jessica',
            'Isla', 'Evie', 'Florence', 'Willow', 'Ivy', 'Rosie', 'Daisy', 'Ruby', 'Sienna', 'Harper',
            'Alice', 'Matilda', 'Erin', 'Maya', 'Millie', 'Eva', 'Esme', 'Bella', 'Layla', 'Penelope',
            'Violet', 'Elsie', 'Nancy', 'Aurora', 'Eliza', 'Abigail', 'Lola', 'Imogen', 'Zara', 'Maisie',
            'Eleanor', 'Molly', 'Ada', 'Clara', 'Thea', 'Anna', 'Harriet', 'Isabelle', 'Rose', 'Lexi',
            'Arabella', 'Eden', 'Orla', 'Amber', 'Lydia', 'Maria', 'Bonnie', 'Beatrice', 'Iris', 'Summer',
            'Georgia', 'Lottie', 'Robyn', 'Scarlett', 'Sara', 'Holly', 'Fiona', 'Niamh', 'Cora', 'Luna',
        ],
        'last': [
            'Smith', 'Jones', 'Williams', 'Taylor', 'Brown', 'Davies', 'Evans', 'Wilson', 'Thomas', 'Roberts',
            'Johnson', 'Lewis', 'Walker', 'Robinson', 'Wood', 'Thompson', 'White', 'Watson', 'Jackson', 'Wright',
            'Green', 'Harris', 'Cooper', 'King', 'Lee', 'Martin', 'Clarke', 'James', 'Morgan', 'Hughes',
            'Edwards', 'Hill', 'Moore', 'Clark', 'Harrison', 'Scott', 'Young', 'Morris', 'Hall', 'Ward',
            'Turner', 'Carter', 'Phillips', 'Mitchell', 'Patel', 'Adams', 'Campbell', 'Anderson', 'Allen', 'Cook',
            'Bailey', 'Parker', 'Miller', 'Davis', 'Murphy', 'Price', 'Bell', 'Kelly', 'Bennett', 'Griffiths',
            'Knight', 'Lloyd', 'Barker', 'Fisher', 'Palmer', 'Holmes', 'Mills', 'Berry', 'Mason', 'Hunt',
            'Barnes', 'Gray', 'Stone', 'Stevens', 'Spencer', 'Webb', 'Collins', 'Grant', 'Hamilton', 'Gibson',
        ],
    },
    'Italy': {
        'first_male': [
            'Marco', 'Giuseppe', 'Giovanni', 'Antonio', 'Francesco', 'Mario', 'Luigi', 'Alessandro', 'Andrea', 'Luca',
            'Roberto', 'Stefano', 'Angelo', 'Massimo', 'Pietro', 'Paolo', 'Salvatore', 'Vincenzo', 'Domenico', 'Matteo',
            'Davide', 'Michele', 'Lorenzo', 'Fabio', 'Giorgio', 'Riccardo', 'Claudio', 'Gianluca', 'Nicola', 'Federico',
            'Emanuele', 'Simone', 'Daniele', 'Alberto', 'Enrico', 'Filippo', 'Sergio', 'Leonardo', 'Tommaso', 'Giacomo',
            'Edoardo', 'Diego', 'Gabriele', 'Carlo', 'Giancarlo', 'Maurizio', 'Franco', 'Dario', 'Vittorio', 'Fabrizio',
            'Alessio', 'Christian', 'Manuel', 'Cristian', 'Oscar', 'Bruno', 'Sandro', 'Enzo', 'Raffaele', 'Piero',
            'Mauro', 'Cesare', 'Alfredo', 'Adriano', 'Luciano', 'Renato', 'Silvio', 'Gennaro', 'Armando', 'Umberto',
            'Rocco', 'Guido', 'Aldo', 'Flavio', 'Ivano', 'Giuliano', 'Fernando', 'Orlando', 'Ernesto', 'Beppe',
        ],
        'first_female': [
            'Maria', 'Anna', 'Giulia', 'Francesca', 'Chiara', 'Sara', 'Laura', 'Valentina', 'Alessia', 'Elena',
            'Federica', 'Martina', 'Silvia', 'Giorgia', 'Elisa', 'Roberta', 'Monica', 'Simona', 'Claudia', 'Paola',
            'Cristina', 'Serena', 'Ilaria', 'Daniela', 'Barbara', 'Stefania', 'Veronica', 'Emanuela', 'Patrizia', 'Antonella',
            'Angela', 'Michela', 'Lucia', 'Manuela', 'Eleonora', 'Sofia', 'Alice', 'Aurora', 'Beatrice', 'Carlotta',
            'Camilla', 'Carolina', 'Cecilia', 'Caterina', 'Diana', 'Elisabetta', 'Emilia', 'Fabiola', 'Flavia', 'Gabriella',
            'Gaia', 'Ginevra', 'Irene', 'Isabella', 'Letizia', 'Linda', 'Lorena', 'Ludovica', 'Margherita', 'Miriam',
            'Nadia', 'Noemi', 'Pamela', 'Rachele', 'Rebecca', 'Rita', 'Rosa', 'Samantha', 'Sandra', 'Sonia',
            'Teresa', 'Tiziana', 'Vanessa', 'Virginia', 'Viola', 'Viviana', 'Emma', 'Nicole', 'Matilde', 'Benedetta',
        ],
        'last': [
            'Rossi', 'Russo', 'Ferrari', 'Esposito', 'Bianchi', 'Romano', 'Colombo', 'Ricci', 'Marino', 'Greco',
            'Bruno', 'Gallo', 'Conti', 'De Luca', 'Costa', 'Giordano', 'Mancini', 'Rizzo', 'Lombardi', 'Moretti',
            'Barbieri', 'Fontana', 'Santoro', 'Mariani', 'Rinaldi', 'Caruso', 'Ferrara', 'Galli', 'Martini', 'Leone',
            'Longo', 'Gentile', 'Martinelli', 'Vitale', 'Lombardo', 'Serra', 'Coppola', 'De Santis', 'DAngelo', 'Marchetti',
            'Parisi', 'Villa', 'Conte', 'Ferraro', 'Ferri', 'Fabbri', 'Bianco', 'Marini', 'Grasso', 'Valentini',
            'Messina', 'Sala', 'De Angelis', 'Gatti', 'Pellegrini', 'Palumbo', 'Sanna', 'Farina', 'Rizzi', 'Monti',
            'Cattaneo', 'Morandi', 'Riva', 'Donati', 'Piras', 'Vitali', 'Battaglia', 'Sartori', 'Neri', 'Testa',
            'Bernardi', 'Grassi', 'Basile', 'Sorrentino', 'Poli', 'Benedetti', 'Carbone', 'DAmico', 'Orlando', 'Silvestri',
        ],
    },
    'France': {
        'first_male': [
            'Jean', 'Pierre', 'Michel', 'Andre', 'Philippe', 'Rene', 'Louis', 'Alain', 'Jacques', 'Bernard',
            'Francois', 'Marcel', 'Robert', 'Henri', 'Paul', 'Claude', 'Eric', 'Nicolas', 'Thomas', 'Alexandre',
            'Julien', 'Antoine', 'Maxime', 'Lucas', 'Hugo', 'Gabriel', 'Leo', 'Raphael', 'Arthur', 'Nathan',
            'Mathis', 'Ethan', 'Noah', 'Theo', 'Adam', 'Louis', 'Victor', 'Clement', 'Baptiste', 'Romain',
            'Quentin', 'Valentin', 'Adrien', 'Florian', 'Dylan', 'Kevin', 'Jeremy', 'Guillaume', 'Sebastien', 'David',
            'Stephane', 'Christophe', 'Cedric', 'Olivier', 'Fabien', 'Sylvain', 'Vincent', 'Damien', 'Yannick', 'Bruno',
            'Thierry', 'Patrick', 'Frederic', 'Laurent', 'Didier', 'Pascal', 'Serge', 'Gilles', 'Raymond', 'Roger',
            'Marc', 'Daniel', 'Dominique', 'Maurice', 'Georges', 'Christian', 'Lucien', 'Yves', 'Francis', 'Gerard',
        ],
        'first_female': [
            'Marie', 'Jeanne', 'Francoise', 'Monique', 'Catherine', 'Nathalie', 'Isabelle', 'Sylvie', 'Anne', 'Martine',
            'Camille', 'Lea', 'Emma', 'Manon', 'Chloe', 'Ines', 'Louise', 'Jade', 'Sarah', 'Elodie',
            'Julie', 'Sophie', 'Charlotte', 'Alice', 'Clara', 'Rose', 'Anna', 'Lola', 'Nina', 'Lucie',
            'Celine', 'Aurelie', 'Pauline', 'Sandrine', 'Caroline', 'Virginie', 'Laetitia', 'Stephanie', 'Veronique', 'Valerie',
            'Helene', 'Brigitte', 'Danielle', 'Michele', 'Genevieve', 'Odette', 'Simone', 'Jacqueline', 'Yvonne', 'Madeleine',
            'Florence', 'Patricia', 'Corinne', 'Christine', 'Delphine', 'Emilie', 'Laura', 'Marine', 'Marion', 'Melanie',
            'Oceane', 'Amandine', 'Clemence', 'Mathilde', 'Margot', 'Eva', 'Zoe', 'Victoria', 'Alexandra', 'Juliette',
            'Elise', 'Agathe', 'Anais', 'Romane', 'Apolline', 'Capucine', 'Margaux', 'Lena', 'Ambre', 'Maelys',
        ],
        'last': [
            'Martin', 'Bernard', 'Dubois', 'Thomas', 'Robert', 'Richard', 'Petit', 'Durand', 'Leroy', 'Moreau',
            'Simon', 'Laurent', 'Lefebvre', 'Michel', 'Garcia', 'David', 'Bertrand', 'Roux', 'Vincent', 'Fournier',
            'Morel', 'Girard', 'Andre', 'Lefevre', 'Mercier', 'Dupont', 'Lambert', 'Bonnet', 'Francois', 'Martinez',
            'Legrand', 'Garnier', 'Faure', 'Rousseau', 'Blanc', 'Guerin', 'Muller', 'Henry', 'Roussel', 'Nicolas',
            'Perrin', 'Morin', 'Mathieu', 'Clement', 'Gauthier', 'Dumont', 'Lopez', 'Fontaine', 'Chevalier', 'Robin',
            'Masson', 'Sanchez', 'Gerard', 'Nguyen', 'Boyer', 'Denis', 'Lemaire', 'Duval', 'Joly', 'Gautier',
            'Roger', 'Roche', 'Roy', 'Noel', 'Meyer', 'Lucas', 'Meunier', 'Jean', 'Perez', 'Marchand',
            'Dufour', 'Blanchard', 'Marie', 'Barbier', 'Brun', 'Dumas', 'Brunet', 'Schmitt', 'Leroux', 'Colin',
        ],
    },
    'Spain': {
        'first_male': [
            'Antonio', 'Jose', 'Manuel', 'Francisco', 'David', 'Juan', 'Javier', 'Daniel', 'Carlos', 'Jesus',
            'Alejandro', 'Miguel', 'Rafael', 'Pedro', 'Pablo', 'Angel', 'Fernando', 'Luis', 'Alberto', 'Sergio',
            'Diego', 'Adrian', 'Alvaro', 'Raul', 'Jorge', 'Ivan', 'Ruben', 'Oscar', 'Roberto', 'Enrique',
            'Victor', 'Mario', 'Andres', 'Ramon', 'Marcos', 'Jaime', 'Guillermo', 'Eduardo', 'Ignacio', 'Emilio',
            'Martin', 'Hugo', 'Marc', 'Gonzalo', 'Nicolas', 'Samuel', 'Tomas', 'Hector', 'Lorenzo', 'Ricardo',
            'Salvador', 'Joaquin', 'Julian', 'Cesar', 'Cristian', 'Alfonso', 'Santiago', 'Felix', 'German', 'Arturo',
            'Agustin', 'Rodrigo', 'Gabriel', 'Ismael', 'Felipe', 'Aitor', 'Iker', 'Jon', 'Pau', 'Gerard',
            'Jordi', 'Xavier', 'Pere', 'Josep', 'Joan', 'Oriol', 'Arnau', 'Miquel', 'Carles', 'Ferran',
        ],
        'first_female': [
            'Maria', 'Carmen', 'Ana', 'Isabel', 'Laura', 'Cristina', 'Marta', 'Lucia', 'Elena', 'Rosa',
            'Paula', 'Sara', 'Claudia', 'Andrea', 'Silvia', 'Raquel', 'Patricia', 'Beatriz', 'Natalia', 'Alba',
            'Sofia', 'Marina', 'Irene', 'Julia', 'Nuria', 'Alicia', 'Angela', 'Sandra', 'Monica', 'Eva',
            'Teresa', 'Pilar', 'Dolores', 'Josefa', 'Antonia', 'Francisca', 'Manuela', 'Concepcion', 'Mercedes', 'Rocio',
            'Inmaculada', 'Amparo', 'Victoria', 'Esther', 'Susana', 'Carolina', 'Miriam', 'Lorena', 'Veronica', 'Celia',
            'Noelia', 'Vanessa', 'Yolanda', 'Nerea', 'Aitana', 'Carla', 'Emma', 'Valentina', 'Abril', 'Vega',
            'Laia', 'Martina', 'Daniela', 'Adriana', 'Ines', 'Lola', 'Belen', 'Diana', 'Lidia', 'Olga',
            'Gemma', 'Anna', 'Montse', 'Mireia', 'Clara', 'Ariadna', 'Helena', 'Naia', 'Ane', 'Leire',
        ],
        'last': [
            'Garcia', 'Rodriguez', 'Martinez', 'Lopez', 'Gonzalez', 'Hernandez', 'Perez', 'Sanchez', 'Ramirez', 'Torres',
            'Flores', 'Rivera', 'Gomez', 'Diaz', 'Reyes', 'Morales', 'Jimenez', 'Ruiz', 'Alvarez', 'Romero',
            'Alonso', 'Navarro', 'Gutierrez', 'Munoz', 'Dominguez', 'Vazquez', 'Ramos', 'Gil', 'Serrano', 'Blanco',
            'Molina', 'Moreno', 'Suarez', 'Ortega', 'Delgado', 'Castro', 'Ortiz', 'Rubio', 'Marin', 'Sanz',
            'Iglesias', 'Nunez', 'Medina', 'Garrido', 'Cortes', 'Castillo', 'Santos', 'Lozano', 'Guerrero', 'Cano',
            'Prieto', 'Mendez', 'Cruz', 'Calvo', 'Gallego', 'Vidal', 'Leon', 'Herrero', 'Marquez', 'Pena',
            'Cabrera', 'Martin', 'Fuentes', 'Carrasco', 'Aguilar', 'Vega', 'Campos', 'Ferrer', 'Pascual', 'Herrera',
            'Caballero', 'Vicente', 'Gimenez', 'Soler', 'Lorenzo', 'Pastor', 'Mora', 'Vargas', 'Rey', 'Santiago',
        ],
    },
    'Germany': {
        'first_male': [
            'Michael', 'Thomas', 'Andreas', 'Stefan', 'Christian', 'Markus', 'Daniel', 'Martin', 'Alexander', 'Jan',
            'Matthias', 'Peter', 'Frank', 'Klaus', 'Jurgen', 'Wolfgang', 'Hans', 'Dieter', 'Uwe', 'Bernd',
            'Sebastian', 'Lukas', 'Florian', 'Tobias', 'Felix', 'Jonas', 'Maximilian', 'Paul', 'Leon', 'Tim',
            'David', 'Philipp', 'Niklas', 'Julian', 'Moritz', 'Johannes', 'Simon', 'Fabian', 'Kevin', 'Marcel',
            'Patrick', 'Dennis', 'Benjamin', 'Manuel', 'Dominik', 'Marco', 'Sascha', 'Oliver', 'Christoph', 'Sven',
            'Torsten', 'Holger', 'Ralf', 'Jochen', 'Volker', 'Werner', 'Karl', 'Heinz', 'Heinrich', 'Friedrich',
            'Wilhelm', 'Hermann', 'Rudolf', 'Walter', 'Ernst', 'Otto', 'Gerhard', 'Helmut', 'Manfred', 'Horst',
            'Rainer', 'Norbert', 'Joachim', 'Reinhard', 'Harald', 'Detlef', 'Axel', 'Karsten', 'Dirk', 'Ingo',
        ],
        'first_female': [
            'Maria', 'Ursula', 'Monika', 'Petra', 'Sabine', 'Andrea', 'Anna', 'Brigitte', 'Christine', 'Claudia',
            'Julia', 'Sophie', 'Emma', 'Mia', 'Hannah', 'Lea', 'Lena', 'Sarah', 'Lisa', 'Laura',
            'Marie', 'Johanna', 'Charlotte', 'Sophia', 'Emilia', 'Lina', 'Amelie', 'Luisa', 'Clara', 'Paula',
            'Katharina', 'Nicole', 'Sandra', 'Melanie', 'Stefanie', 'Christina', 'Birgit', 'Karin', 'Angelika', 'Gabriele',
            'Susanne', 'Martina', 'Heike', 'Marion', 'Silke', 'Daniela', 'Anja', 'Tanja', 'Simone', 'Nadine',
            'Jana', 'Jasmin', 'Vanessa', 'Jennifer', 'Michelle', 'Jessica', 'Caroline', 'Franziska', 'Kathrin', 'Miriam',
            'Nathalie', 'Antje', 'Doreen', 'Mandy', 'Katja', 'Ute', 'Renate', 'Ingrid', 'Helga', 'Gisela',
            'Erika', 'Gertrud', 'Elisabeth', 'Ruth', 'Elfriede', 'Margarete', 'Hildegard', 'Frieda', 'Rosa', 'Klara',
        ],
        'last': [
            'Muller', 'Schmidt', 'Schneider', 'Fischer', 'Weber', 'Meyer', 'Wagner', 'Becker', 'Schulz', 'Hoffmann',
            'Schafer', 'Koch', 'Bauer', 'Richter', 'Klein', 'Wolf', 'Schroder', 'Neumann', 'Schwarz', 'Zimmermann',
            'Braun', 'Kruger', 'Hofmann', 'Hartmann', 'Lange', 'Schmitt', 'Werner', 'Schmitz', 'Krause', 'Meier',
            'Lehmann', 'Schmid', 'Schulze', 'Maier', 'Kohler', 'Herrmann', 'Konig', 'Walter', 'Mayer', 'Huber',
            'Kaiser', 'Fuchs', 'Peters', 'Lang', 'Scholz', 'Moller', 'Weiss', 'Jung', 'Hahn', 'Schubert',
            'Vogel', 'Friedrich', 'Keller', 'Gunther', 'Frank', 'Berger', 'Winkler', 'Roth', 'Beck', 'Lorenz',
            'Baumann', 'Franke', 'Albrecht', 'Schuster', 'Simon', 'Ludwig', 'Bohm', 'Winter', 'Kramer', 'Vogt',
            'Stein', 'Jager', 'Otto', 'Sommer', 'Gross', 'Seidel', 'Heinrich', 'Brandt', 'Haas', 'Schreiber',
        ],
    },
    'Japan': {
        'first_male': [
            'Haruki', 'Yuki', 'Takeshi', 'Kenji', 'Hiroshi', 'Kazuki', 'Ryota', 'Shota', 'Daisuke', 'Yuto',
            'Hayato', 'Kenta', 'Sho', 'Ren', 'Naoki', 'Ryu', 'Masashi', 'Taro', 'Akira', 'Koji',
            'Takumi', 'Yuji', 'Makoto', 'Shinji', 'Daiki', 'Yuma', 'Kaito', 'Sota', 'Haruto', 'Minato',
            'Aoi', 'Hiroto', 'Yamato', 'Riku', 'Souta', 'Hinata', 'Asahi', 'Itsuki', 'Yuuto', 'Eita',
            'Kazuya', 'Satoshi', 'Tetsuya', 'Hideki', 'Tomoya', 'Shoichi', 'Noboru', 'Isamu', 'Masato', 'Kenichi',
            'Toshio', 'Yoshio', 'Kunio', 'Akio', 'Masao', 'Takeo', 'Susumu', 'Osamu', 'Minoru', 'Kiyoshi',
            'Seiji', 'Yasuo', 'Tadashi', 'Koichi', 'Shingo', 'Yusuke', 'Wataru', 'Kohei', 'Naoya', 'Masaya',
            'Teppei', 'Shunsuke', 'Kosuke', 'Keisuke', 'Ryosuke', 'Shun', 'Tsuyoshi', 'Kensuke', 'Goro', 'Ichiro',
        ],
        'first_female': [
            'Yuki', 'Sakura', 'Aoi', 'Hana', 'Yui', 'Rin', 'Mio', 'Mei', 'Akari', 'Haruka',
            'Nanami', 'Ayaka', 'Saki', 'Mika', 'Emi', 'Yuna', 'Riko', 'Miyu', 'Kana', 'Nana',
            'Himari', 'Yua', 'Hinata', 'Koharu', 'Akane', 'Ichika', 'Sana', 'Kokona', 'Mana', 'Shiori',
            'Yuki', 'Mizuki', 'Misaki', 'Mai', 'Asuka', 'Nozomi', 'Chihiro', 'Tomoko', 'Yoko', 'Keiko',
            'Mariko', 'Mayumi', 'Kyoko', 'Naoko', 'Kumiko', 'Sachiko', 'Yoshiko', 'Junko', 'Noriko', 'Etsuko',
            'Kazuko', 'Miyuki', 'Yumiko', 'Takako', 'Masako', 'Fusako', 'Satoko', 'Hideko', 'Teruko', 'Shizuko',
            'Michiko', 'Nobuko', 'Yasuko', 'Kimiko', 'Setsuko', 'Toshiko', 'Haruko', 'Chieko', 'Reiko', 'Mitsuko',
            'Kaho', 'Tsubasa', 'Momoka', 'Honoka', 'Kanon', 'Kotone', 'Airi', 'Sara', 'Miki', 'Aya',
        ],
        'last': [
            'Sato', 'Suzuki', 'Takahashi', 'Tanaka', 'Watanabe', 'Ito', 'Yamamoto', 'Nakamura', 'Kobayashi', 'Kato',
            'Yoshida', 'Yamada', 'Sasaki', 'Yamaguchi', 'Matsumoto', 'Inoue', 'Kimura', 'Hayashi', 'Shimizu', 'Mori',
            'Saito', 'Ikeda', 'Hashimoto', 'Yamashita', 'Ishikawa', 'Nakajima', 'Maeda', 'Fujita', 'Ogawa', 'Okada',
            'Goto', 'Hasegawa', 'Murakami', 'Kondo', 'Ishii', 'Aoki', 'Sakamoto', 'Fukuda', 'Endo', 'Nishimura',
            'Fujii', 'Ota', 'Miura', 'Kaneko', 'Fujiwara', 'Okamoto', 'Nakano', 'Abe', 'Ueda', 'Harada',
            'Matsuda', 'Ono', 'Takeuchi', 'Kawaguchi', 'Shimada', 'Sugiyama', 'Higashi', 'Nagai', 'Otsuka', 'Chiba',
            'Kubo', 'Kawasaki', 'Noguchi', 'Miyazaki', 'Uchida', 'Shibata', 'Sakurai', 'Kinoshita', 'Hara', 'Matsui',
            'Nomura', 'Wada', 'Arai', 'Kitamura', 'Tamura', 'Hirano', 'Honda', 'Fukushima', 'Iwata', 'Kuroda',
        ],
    },
    'India': {
        'first_male': [
            'Raj', 'Amit', 'Vikram', 'Rahul', 'Arun', 'Suresh', 'Vijay', 'Sanjay', 'Ajay', 'Manoj',
            'Ravi', 'Krishna', 'Deepak', 'Anil', 'Rajesh', 'Mukesh', 'Sunil', 'Pradeep', 'Rakesh', 'Ashok',
            'Vivek', 'Sandeep', 'Nitin', 'Sachin', 'Rohit', 'Mohit', 'Gaurav', 'Karan', 'Arjun', 'Varun',
            'Vishal', 'Aman', 'Ankit', 'Kunal', 'Nikhil', 'Pawan', 'Naveen', 'Harish', 'Girish', 'Ramesh',
            'Ganesh', 'Mahesh', 'Prakash', 'Dinesh', 'Naresh', 'Yogesh', 'Hitesh', 'Jitesh', 'Nilesh', 'Rajat',
            'Vikas', 'Neeraj', 'Shiv', 'Om', 'Dev', 'Ishaan', 'Kabir', 'Yash', 'Dhruv', 'Aditya',
            'Siddharth', 'Akash', 'Aarav', 'Vihaan', 'Reyansh', 'Ayaan', 'Aryan', 'Pranav', 'Advait', 'Shaurya',
            'Atharv', 'Ved', 'Rudra', 'Lakshya', 'Parth', 'Chirag', 'Rohan', 'Tushar', 'Tarun', 'Ashish',
        ],
        'first_female': [
            'Priya', 'Anjali', 'Neha', 'Pooja', 'Divya', 'Sneha', 'Kavita', 'Sunita', 'Meena', 'Rekha',
            'Anita', 'Deepa', 'Lakshmi', 'Radha', 'Geeta', 'Sita', 'Asha', 'Seema', 'Nisha', 'Ritu',
            'Swati', 'Shweta', 'Preeti', 'Komal', 'Manisha', 'Rashmi', 'Sapna', 'Suman', 'Mamta', 'Jyoti',
            'Kiran', 'Rani', 'Shanti', 'Usha', 'Lata', 'Padma', 'Sarita', 'Kamla', 'Saroj', 'Pushpa',
            'Maya', 'Tara', 'Leela', 'Veena', 'Meera', 'Durga', 'Parvati', 'Indira', 'Sushma', 'Archana',
            'Aishwarya', 'Kiara', 'Ananya', 'Diya', 'Aaradhya', 'Sara', 'Ishita', 'Aditi', 'Avni', 'Mira',
            'Tanvi', 'Kriti', 'Isha', 'Riya', 'Shreya', 'Trisha', 'Nidhi', 'Sakshi', 'Khushi', 'Anika',
            'Navya', 'Myra', 'Pari', 'Saanvi', 'Shanaya', 'Riddhi', 'Siddhi', 'Zara', 'Tanya', 'Simran',
        ],
        'last': [
            'Sharma', 'Patel', 'Singh', 'Kumar', 'Gupta', 'Shah', 'Mehta', 'Kapoor', 'Chopra', 'Malhotra',
            'Joshi', 'Reddy', 'Rao', 'Verma', 'Agarwal', 'Mishra', 'Das', 'Nair', 'Menon', 'Pillai',
            'Khan', 'Iyer', 'Desai', 'Bhat', 'Hegde', 'Patil', 'Kulkarni', 'Shetty', 'Naidu', 'Murthy',
            'Choudhury', 'Banerjee', 'Mukherjee', 'Chatterjee', 'Roy', 'Sen', 'Bose', 'Ghosh', 'Dutta', 'Dey',
            'Saxena', 'Sinha', 'Thakur', 'Pandey', 'Tiwari', 'Dubey', 'Trivedi', 'Dwivedi', 'Shukla', 'Chauhan',
            'Yadav', 'Rawat', 'Negi', 'Bisht', 'Bhatt', 'Jain', 'Goel', 'Mittal', 'Bansal', 'Arora',
            'Sethi', 'Batra', 'Khanna', 'Ahuja', 'Vohra', 'Kohli', 'Bajaj', 'Dhawan', 'Tandon', 'Luthra',
            'Mehra', 'Kashyap', 'Anand', 'Khurana', 'Sood', 'Bhardwaj', 'Kaur', 'Gill', 'Sandhu', 'Dhillon',
        ],
    },
    'Brazil': {
        'first_male': [
            'Pedro', 'Lucas', 'Gabriel', 'Joao', 'Matheus', 'Rafael', 'Gustavo', 'Felipe', 'Bruno', 'Leonardo',
            'Rodrigo', 'Daniel', 'Andre', 'Marcos', 'Paulo', 'Thiago', 'Diego', 'Eduardo', 'Fernando', 'Carlos',
            'Vinicius', 'Arthur', 'Enzo', 'Bernardo', 'Nicolas', 'Henrique', 'Caio', 'Miguel', 'Guilherme', 'Samuel',
            'Davi', 'Lorenzo', 'Heitor', 'Theo', 'Murilo', 'Pietro', 'Benicio', 'Benjamin', 'Igor', 'Yuri',
            'Anderson', 'Alex', 'Wallace', 'Wesley', 'Douglas', 'Victor', 'Alexandre', 'Ricardo', 'Leandro', 'Marcio',
            'Junior', 'Claudio', 'Fabio', 'Sergio', 'Roberto', 'Antonio', 'Francisco', 'Jose', 'Luis', 'Julio',
            'Renato', 'Luciano', 'Adriano', 'Rogerio', 'Flavio', 'Gilberto', 'Edson', 'Alisson', 'Patrick', 'Jefferson',
            'Washington', 'Willian', 'Cleber', 'Everton', 'Cristiano', 'Luiz', 'Marcelino', 'Vagner', 'Renan', 'Otavio',
        ],
        'first_female': [
            'Ana', 'Maria', 'Julia', 'Beatriz', 'Gabriela', 'Mariana', 'Amanda', 'Bruna', 'Camila', 'Fernanda',
            'Leticia', 'Larissa', 'Juliana', 'Patricia', 'Carolina', 'Rafaela', 'Vanessa', 'Isabela', 'Natalia', 'Bianca',
            'Alice', 'Sophia', 'Laura', 'Helena', 'Valentina', 'Luiza', 'Manuela', 'Livia', 'Giovanna', 'Isabella',
            'Lorena', 'Luana', 'Tatiana', 'Renata', 'Aline', 'Priscila', 'Daniela', 'Sabrina', 'Monica', 'Adriana',
            'Simone', 'Sandra', 'Cristiane', 'Carla', 'Paula', 'Luciana', 'Claudia', 'Viviane', 'Rosana', 'Angela',
            'Regina', 'Andreia', 'Elaine', 'Fabiana', 'Cintia', 'Raquel', 'Flavia', 'Roberta', 'Tania', 'Denise',
            'Elisa', 'Clara', 'Cecilia', 'Antonella', 'Maitê', 'Isis', 'Isadora', 'Yasmin', 'Nicole', 'Heloisa',
            'Rebeca', 'Marina', 'Vitoria', 'Emanuele', 'Sara', 'Lara', 'Milena', 'Catarina', 'Agatha', 'Melissa',
        ],
        'last': [
            'Silva', 'Santos', 'Oliveira', 'Souza', 'Rodrigues', 'Ferreira', 'Alves', 'Pereira', 'Lima', 'Gomes',
            'Costa', 'Ribeiro', 'Martins', 'Carvalho', 'Almeida', 'Lopes', 'Soares', 'Fernandes', 'Vieira', 'Barbosa',
            'Rocha', 'Dias', 'Nascimento', 'Andrade', 'Moreira', 'Nunes', 'Marques', 'Machado', 'Mendes', 'Freitas',
            'Cardoso', 'Ramos', 'Gonçalves', 'Santana', 'Teixeira', 'Moura', 'Miranda', 'Pinto', 'Correia', 'Batista',
            'Araujo', 'Monteiro', 'Melo', 'Barros', 'Farias', 'Campos', 'Castro', 'Azevedo', 'Pinheiro', 'Rezende',
            'Borges', 'Cunha', 'Medeiros', 'Duarte', 'Amaral', 'Brito', 'Viana', 'Coelho', 'Bezerra', 'Leite',
            'Siqueira', 'Matos', 'Aguiar', 'Fonseca', 'Reis', 'Tavares', 'Nogueira', 'Guimaraes', 'Leal', 'Paiva',
            'Carmo', 'Pessoa', 'Xavier', 'Carneiro', 'Assis', 'Chaves', 'Macedo', 'Sousa', 'Amorim', 'Prado',
        ],
    },
    'South Korea': {
        'first_male': [
            'Min-jun', 'Seo-jun', 'Do-yun', 'Ye-jun', 'Si-u', 'Ha-jun', 'Jun-seo', 'Ji-ho', 'Jun-woo', 'Hyun-woo',
            'Ji-hoon', 'Seung-min', 'Jun-young', 'Tae-hyung', 'Min-ho', 'Jae-won', 'Sung-min', 'Woo-jin', 'Dong-hyun', 'Kyung-min',
            'Jin-woo', 'Sung-hoon', 'Hyun-jin', 'Tae-min', 'Jae-hyun', 'Young-ho', 'Seung-ho', 'Jun-ho', 'Min-seok', 'Woo-sung',
            'Dong-wook', 'Jung-woo', 'Sang-woo', 'Hyun-seok', 'Jin-ho', 'Tae-woo', 'Joon-ki', 'Seung-gi', 'Won-bin', 'Jong-suk',
            'Soo-hyun', 'Gong-yoo', 'Joong-ki', 'In-sung', 'Hae-in', 'Byung-hun', 'Jung-hwan', 'Chan-woo', 'Jae-beom', 'Young-jae',
        ],
        'first_female': [
            'Seo-yeon', 'Ha-yoon', 'Ji-woo', 'Seo-yun', 'Ji-yoo', 'Ye-eun', 'Chae-won', 'Min-seo', 'So-yeon', 'Yu-na',
            'Ji-min', 'Ye-ji', 'Hye-jin', 'Soo-jin', 'Eun-ji', 'Yoon-ah', 'Ha-na', 'Mi-young', 'Sun-hee', 'Jin-ah',
            'Su-bin', 'Yoo-jin', 'Hye-won', 'Soo-yeon', 'Min-ji', 'Eun-bi', 'Da-hye', 'Ji-young', 'Seul-ki', 'Hae-in',
            'Bo-young', 'Shin-hye', 'Min-ah', 'Ji-eun', 'Ye-won', 'So-min', 'Yeon-seo', 'In-na', 'Hyo-jin', 'Go-eun',
            'Sung-kyung', 'Ji-hyo', 'Soo-hyun', 'Hyo-ri', 'Yoo-ri', 'Sun-mi', 'Tae-yeon', 'Soo-young', 'Yu-ri', 'Jessica',
        ],
        'last': [
            'Kim', 'Lee', 'Park', 'Choi', 'Jeong', 'Kang', 'Cho', 'Yoon', 'Jang', 'Lim',
            'Han', 'Oh', 'Seo', 'Shin', 'Kwon', 'Hwang', 'Ahn', 'Song', 'Yu', 'Hong',
            'Yoo', 'Ko', 'Moon', 'Yang', 'Son', 'Bae', 'Baek', 'Heo', 'Nam', 'Sim',
            'Ryu', 'Ha', 'Jeon', 'Gwak', 'Sung', 'Cha', 'Min', 'Won', 'Jin', 'Ji',
        ],
    },
    'China': {
        'first_male': [
            'Wei', 'Fang', 'Lei', 'Yang', 'Jun', 'Jie', 'Chao', 'Ming', 'Tao', 'Long',
            'Hao', 'Bo', 'Peng', 'Feng', 'Kai', 'Qiang', 'Gang', 'Xin', 'Yu', 'Chen',
            'Jian', 'Liang', 'Dong', 'Hui', 'Bin', 'Wen', 'Yi', 'Zheng', 'Xiang', 'Nan',
            'Shi', 'Yong', 'Ping', 'Lin', 'Hong', 'Guo', 'Zhi', 'Hai', 'Ting', 'Rui',
            'Shen', 'Xiao', 'An', 'Kun', 'Zhen', 'Yuan', 'Qian', 'Hua', 'Yan', 'Bao',
        ],
        'first_female': [
            'Li', 'Na', 'Yan', 'Juan', 'Xiu', 'Jing', 'Mei', 'Ying', 'Hong', 'Fang',
            'Min', 'Hua', 'Lan', 'Qing', 'Xia', 'Ling', 'Ping', 'Xue', 'Hui', 'Dan',
            'Wei', 'Yun', 'Fen', 'Zhen', 'Ai', 'Sha', 'Lin', 'Qiu', 'Chun', 'Rui',
            'Yi', 'Shan', 'Yu', 'Chen', 'Yue', 'Han', 'Tian', 'Lu', 'Si', 'Xi',
            'Ke', 'An', 'Ning', 'Jia', 'Ya', 'Qian', 'Jun', 'Meng', 'Rou', 'Zhu',
        ],
        'last': [
            'Wang', 'Li', 'Zhang', 'Liu', 'Chen', 'Yang', 'Huang', 'Zhao', 'Wu', 'Zhou',
            'Xu', 'Sun', 'Ma', 'Hu', 'Guo', 'Lin', 'He', 'Luo', 'Gao', 'Zheng',
            'Liang', 'Xie', 'Song', 'Tang', 'Xu', 'Han', 'Feng', 'Deng', 'Cao', 'Peng',
            'Zeng', 'Xiao', 'Tian', 'Dong', 'Yuan', 'Pan', 'Yu', 'Jiang', 'Cai', 'Wei',
            'Jia', 'Fu', 'Xia', 'Lu', 'Shi', 'Gu', 'Du', 'Shen', 'Su', 'Ye',
        ],
    },
    'Mexico': {
        'first_male': [
            'Jose', 'Juan', 'Miguel', 'Carlos', 'Luis', 'Francisco', 'Pedro', 'Antonio', 'Jesus', 'Jorge',
            'Manuel', 'Ricardo', 'Alejandro', 'Fernando', 'Rafael', 'Roberto', 'Eduardo', 'Diego', 'Sergio', 'Daniel',
            'David', 'Hector', 'Marco', 'Victor', 'Mario', 'Omar', 'Raul', 'Oscar', 'Enrique', 'Alberto',
            'Arturo', 'Javier', 'Adrian', 'Ivan', 'Andres', 'Rodrigo', 'Gustavo', 'Hugo', 'Angel', 'Pablo',
            'Emilio', 'Santiago', 'Sebastian', 'Mateo', 'Leonardo', 'Nicolas', 'Iker', 'Gael', 'Ian', 'Alan',
        ],
        'first_female': [
            'Maria', 'Guadalupe', 'Rosa', 'Ana', 'Carmen', 'Patricia', 'Margarita', 'Elena', 'Teresa', 'Josefina',
            'Sofia', 'Valentina', 'Camila', 'Ximena', 'Fernanda', 'Daniela', 'Regina', 'Lucia', 'Natalia', 'Isabella',
            'Laura', 'Monica', 'Adriana', 'Claudia', 'Veronica', 'Alejandra', 'Gabriela', 'Diana', 'Karla', 'Sandra',
            'Leticia', 'Elizabeth', 'Silvia', 'Martha', 'Gloria', 'Alicia', 'Irma', 'Beatriz', 'Rocio', 'Yolanda',
            'Renata', 'Victoria', 'Mariana', 'Paula', 'Andrea', 'Michelle', 'Paola', 'Vanessa', 'Jessica', 'Carolina',
        ],
        'last': [
            'Garcia', 'Hernandez', 'Lopez', 'Martinez', 'Gonzalez', 'Rodriguez', 'Perez', 'Sanchez', 'Ramirez', 'Cruz',
            'Flores', 'Gomez', 'Morales', 'Vazquez', 'Jimenez', 'Reyes', 'Diaz', 'Torres', 'Gutierrez', 'Ruiz',
            'Mendoza', 'Aguilar', 'Ortiz', 'Castillo', 'Moreno', 'Rivera', 'Ramos', 'Romero', 'Herrera', 'Medina',
            'Chavez', 'Vargas', 'Velazquez', 'Castro', 'Salazar', 'Delgado', 'Guzman', 'Leon', 'Soto', 'Alvarado',
            'Contreras', 'Rojas', 'Munoz', 'Juarez', 'Fernandez', 'Dominguez', 'Cervantes', 'Rios', 'Ibarra', 'Espinoza',
        ],
    },
    'Russia': {
        'first_male': [
            'Alexander', 'Dmitry', 'Maxim', 'Sergei', 'Andrei', 'Alexei', 'Artem', 'Ilya', 'Kirill', 'Mikhail',
            'Nikita', 'Matvei', 'Roman', 'Egor', 'Ivan', 'Daniel', 'Daniil', 'Timofei', 'Vladimir', 'Nikolai',
            'Pavel', 'Konstantin', 'Viktor', 'Yuri', 'Denis', 'Oleg', 'Vasily', 'Igor', 'Boris', 'Anatoly',
            'Grigory', 'Evgeny', 'Stanislav', 'Valery', 'Leonid', 'Georgy', 'Yaroslav', 'Ruslan', 'Anton', 'Arkady',
        ],
        'first_female': [
            'Anastasia', 'Maria', 'Daria', 'Anna', 'Sofia', 'Polina', 'Victoria', 'Elizabeth', 'Ekaterina', 'Alexandra',
            'Veronika', 'Alina', 'Valeria', 'Ksenia', 'Milana', 'Arina', 'Eva', 'Kira', 'Uliana', 'Vasilisa',
            'Olga', 'Natalia', 'Tatiana', 'Irina', 'Elena', 'Svetlana', 'Lyudmila', 'Galina', 'Marina', 'Larisa',
            'Nina', 'Vera', 'Tamara', 'Nadezhda', 'Zoya', 'Raisa', 'Valentina', 'Lyubov', 'Alla', 'Diana',
        ],
        'last': [
            'Ivanov', 'Smirnov', 'Kuznetsov', 'Popov', 'Vasilyev', 'Petrov', 'Sokolov', 'Mikhailov', 'Novikov', 'Fedorov',
            'Morozov', 'Volkov', 'Alexeev', 'Lebedev', 'Semenov', 'Egorov', 'Pavlov', 'Kozlov', 'Stepanov', 'Nikolaev',
            'Orlov', 'Andreev', 'Makarov', 'Nikitin', 'Zakharov', 'Zaitsev', 'Solovyov', 'Borisov', 'Yakovlev', 'Grigoriev',
            'Romanov', 'Vorobiev', 'Sergeev', 'Kuzmin', 'Frolov', 'Alexandrov', 'Dmitriev', 'Korolev', 'Gusev', 'Kiselev',
        ],
    },
    'Argentina': {
        'first_male': [
            'Santiago', 'Mateo', 'Thiago', 'Benjamin', 'Joaquin', 'Bautista', 'Santino', 'Valentino', 'Lorenzo', 'Felipe',
            'Juan', 'Martin', 'Lucas', 'Nicolas', 'Agustin', 'Tomas', 'Facundo', 'Gonzalo', 'Federico', 'Leandro',
            'Maximo', 'Franco', 'Bruno', 'German', 'Diego', 'Pablo', 'Rodrigo', 'Sebastian', 'Emiliano', 'Cristian',
        ],
        'first_female': [
            'Sofia', 'Isabella', 'Valentina', 'Emma', 'Martina', 'Lucia', 'Emilia', 'Catalina', 'Olivia', 'Mia',
            'Camila', 'Victoria', 'Josefina', 'Delfina', 'Alma', 'Juana', 'Paula', 'Lola', 'Julieta', 'Florencia',
            'Agustina', 'Micaela', 'Antonella', 'Renata', 'Pilar', 'Sol', 'Abril', 'Clara', 'Rosario', 'Milagros',
        ],
        'last': [
            'Gonzalez', 'Rodriguez', 'Fernandez', 'Lopez', 'Martinez', 'Garcia', 'Perez', 'Sanchez', 'Romero', 'Diaz',
            'Torres', 'Gomez', 'Ruiz', 'Alvarez', 'Suarez', 'Moreno', 'Gutierrez', 'Flores', 'Benitez', 'Acosta',
            'Medina', 'Herrera', 'Aguirre', 'Cabrera', 'Molina', 'Castro', 'Sosa', 'Ortiz', 'Pereyra', 'Silva',
        ],
    },
}

# Genera varianti combinando nomi e cognomi
def get_random_name(nationality: str, gender: str) -> tuple:
    """Genera un nome casuale per nazionalità e genere."""
    import random
    
    if nationality not in EXTENDED_NAMES:
        nationality = random.choice(list(EXTENDED_NAMES.keys()))
    
    names = EXTENDED_NAMES[nationality]
    
    if gender == 'male':
        first_name = random.choice(names['first_male'])
    else:
        first_name = random.choice(names['first_female'])
    
    last_name = random.choice(names['last'])
    
    return first_name, last_name, nationality
